# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8080/user/
Accept: application/json

###
GET http://localhost:8080/user/user111
Accept: application/json

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": "user444",
  "name": "user4",
  "email" : "user44@naver.com"
}

###
PUT http://localhost:8080/user
Content-Type: application/json

{
  "id": "user111",
  "name": "user12",
  "email": "user123@naver.com"
}

###
DELETE http://localhost:8080/user/user111
Accept: application/json

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": "user111",
  "name": "user1",
  "email" : "user11@naver.com"
}

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": "user222",
  "name": "user2",
  "email" : "user22@naver.com"
}

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "id": "user333",
  "name": "user3",
  "email" : "user33@naver.com"
}

###
